apiVersion: 1

datasources:
  - name: grafana-postgresql-datasource
    type: grafana-postgresql-datasource
    uid: fefjij7w4zmdcc
    access: proxy
    url: task_manager-db-1:5432
    user: ${GF_DATABASE_USER}
    database: ${GF_DATABASE}
    jsonData:
      sslmode: "disable"
      postgresVersion: 1500
      timescaledb: false
    secureJsonData:
      password: ${GF_DATABASE_PASSWORD}

  - name: prometheus
    type: prometheus
    uid: defj73iopj37ka
    access: proxy
    url: http://prometheus:9090