"""Initial migration

Revision ID: 570dbf008aec
Revises: b79cbffc56ac
Create Date: 2025-03-08 22:13:37.771599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '570dbf008aec'
down_revision: Union[str, None] = 'b79cbffc56ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_date', sa.JSON(), nullable=False))
        batch_op.drop_column('task_type')
        batch_op.drop_column('file')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('task_type', postgresql.ENUM('FILE_UPLOAD', 'FILE_COPY', 'FILE_DELETE', name='tasktypeenum'), autoincrement=False, nullable=False))
        batch_op.drop_column('task_date')

    # ### end Alembic commands ###
