{
 "title": "Basic Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "HTTP-запросы",
   "type": "timeseries",
   "description": "Количество запросов в секунду по разным эндпоинтам.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (handler)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Среднее время обработки запросов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество задач определенного типа",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT task_data->>'task_type' AS task_type, COUNT(*) AS count\r\nFROM tasks\r\nGROUP BY  task_type;"
    }
   ]
  },
  {
   "title": "Ошибки HTTP за последние 5 минут",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 10, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{status=~\"4..|5..\"}[5m])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Статусы выполнения",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT status, COUNT(*) AS count\r\nFROM tasks\r\nGROUP BY status"
    }
   ]
  }
 ]
}